name: ARMv8 Docker BuildX

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * 6

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  DOCKER_BUILD: buildImageX.sh
  DOCKER_IMAGE: summary/openwrt-aarch64

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Extract OpenWrt Version
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        cd $GITHUB_WORKSPACE/openwrt
        version=$(cat "package/lean/default-settings/files/zzz-default-settings" | grep DISTRIB_REVISION= | awk -F "'" '{print $2}')
        echo "TAG=$version" >> $GITHUB_ENV

    - name: Extract OpenWrt Firmware
      id: download
      run: |
        cd $GITHUB_WORKSPACE/docker
        wget -q $(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/releases" | grep "ARMv8_Docker.*rootfs.tar.gz" | cut -d '"' -f 4)
        chmod +x $DOCKER_BUILD && ./$DOCKER_BUILD
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Set up QEMU
      uses: docker/setup-qemu-action@master

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@master

    - name: Login to Docker Hub
      uses: docker/login-action@master
      with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker
      if: steps.download.outputs.status == 'success'
      uses: docker/build-push-action@master
      with:
        platforms: linux/arm64
        context: docker
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE }}:${{ env.TAG }}
          ${{ env.DOCKER_IMAGE }}
