#===============================================
# Description: Package Armvirt
# File name: package-armvirt.yml
# Lisence: MIT
# Author: OPHUB
# https://github.com/ophub/op
#===============================================

name: Package

on:
  repository_dispatch:
  workflow_dispatch:
  watch:
    types: started

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  UPLOAD_FIRMWARE: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    name: Package for ${{ matrix.version }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: MINI
            explain: 这是精简版本，集成科学上网和去广告插件
          - version: PLUS
            explain: 这是多功能版本，集成一些日常常用插件等

    env:
      VERSION: ${{ matrix.version }}
      EXPLAIN: ${{ matrix.explain }}

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-2004)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        cd openwrt
        useVersionInfo=$(git show -s --date=short --format="Author: %an<br/>date: %cd<br/>commit: %s<br/>commit hash: %H")
        echo "useVersionInfo=$useVersionInfo" >> $GITHUB_ENV
        echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV

    - name: Package armvirt as openwrt
      uses: ophub/flippy-openwrt-actions@main
      env:
        OPENWRT_ARMVIRT: https://github.com/haiibo/OpenWrt/releases/download/ROOTFS_${{ env.VERSION }}/openwrt-armvirt-64-default-rootfs.tar.gz
        PACKAGE_SOC: vplus_beikeyun_l1pro_s905d_s905x3_s922x_s922x-n2
        KERNEL_REPO_URL: https://github.com/ophub/kernel/tree/main/pub/stable
        KERNEL_VERSION_NAME: 5.4.150_5.14.10
        KERNEL_AUTO_LATEST: true
        GZIP_IMGS: .gz

    - name: Upload artifact to actions
      uses: kittaakos/upload-artifact-as-is@master
      if: env.PACKAGED_STATUS == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      with:
        path: ${{ env.PACKAGED_OUTPUTPATH }}/

    - name: Upload openwrt to release
      uses: ncipollo/release-action@v1
      if: env.PACKAGED_STATUS == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        name: R${{ env.DATE }} for ARMv8_${{ env.VERSION }}
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
        allowUpdates: true
        removeArtifacts: true
        tag: ARMv8_${{ env.VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          This is OpenWrt firmware for Armvirt 64
          * ${{ env.EXPLAIN }}
          默认IP：10.10.10.10 默认密码：password
          安装到EMMC：系统 → 晶晨宝盒 → 安装OpenWrt → 选择型号 → 安装
          升级OpenWrt：系统 → 晶晨宝盒 → 手动上传更新 或者 在线下载更新
          当前使用版本:【编译前的最后一次➦[主源码](https://github.com/coolsnowwolf/lede)更新记录】
          ${{ env.useVersionInfo }}
